export const theme = {
    colors: {
        primary: '#005A63',
        secondary: '#FFDDD2',
        background: '#FFFFFF',
        textPrimary: '#FFFFFF',
        textDark: '#333333',
        textInput: '#D8CDC9',
        shadowColor: '#000000',
        firstMatter: '#EDF6F9',
        secondMatter: '#D7E1FD',
        thirdMatter: '#FFDDD2',
        fourthMatter: '#DD8C6A',
        fifthMatter: '#C6FDDB',
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
        xx: 50,
    },
    fontSize: {
        small: 12,
        normal: 16,
        large: 20,
        title: 24,
    },
    fonts: {
        light: 'Inter_300Light',
        bold: 'Inter_700Bold',
    },
    radius:  {
        sm: 4,
        md: 10,
        lg: 50,
        full: 9999,
    },
};
